<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class ColorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * the cities is large, we need to break it in parts
     * @return void
     */
    public function run()
    {
        DB::table('colors')->delete();
        $colors = array(

            // Default Bootstrap color
            array('type' => "bg", 'color' => 'bg-primary', 'hexacode' => "#0d6efd", 'is_default' => 1),
            array('type' => "bg", 'color' => 'bg-secondary', 'hexacode' => "#6c757d", 'is_default' => 1),

            array('type' => "bg", 'color' => 'bg-success', 'hexacode' => "#198754", 'is_default' => 1),
            array('type' => "bg", 'color' => 'bg-danger', 'hexacode' => "#dc3545", 'is_default' => 1),
            array('type' => "bg", 'color' => 'bg-warning', 'hexacode' => "#ffc107", 'is_default' => 1),
            array('type' => "bg", 'color' => 'bg-info', 'hexacode' => "#0dcaf0", 'is_default' => 1),
            array('type' => "bg", 'color' => 'bg-light', 'hexacode' => "#f8f9fa", 'is_default' => 1),
            array('type' => "bg", 'color' => 'bg-dark', 'hexacode' => "#212529", 'is_default' => 1),

            array('type' => "text", 'color' => 'text-primary', 'hexacode' => "#0d6efd", 'is_default' => 1),
            array('type' => "text", 'color' => 'text-secondary', 'hexacode' => "#6c757d", 'is_default' => 1),

            array('type' => "text", 'color' => 'text-success', 'hexacode' => "#198754", 'is_default' => 1),
            array('type' => "text", 'color' => 'text-danger', 'hexacode' => "#dc3545", 'is_default' => 1),
            array('type' => "text", 'color' => 'text-warning', 'hexacode' => "#ffc107", 'is_default' => 1),
            array('type' => "text", 'color' => 'text-info', 'hexacode' => "#0dcaf0", 'is_default' => 1),
            array('type' => "text", 'color' => 'text-light', 'hexacode' => "#f8f9fa", 'is_default' => 1),
            array('type' => "text", 'color' => 'text-dark', 'hexacode' => "#212529", 'is_default' => 1),

            // Black & white

            array('type' => "bg", 'color' => 'black', 'hexacode' => "#000000", 'is_default' => 0),
            array('type' => "bg", 'color' => 'white', 'hexacode' => "#ffffff", 'is_default' => 0),
            array('type' => "text", 'color' => 'black', 'hexacode' => "#000000", 'is_default' => 0),
            array('type' => "text", 'color' => 'white', 'hexacode' => "#ffffff", 'is_default' => 0),

            // Red

            array('type' => "bg", 'color' => 'red-lighten-5', 'hexacode' => "#ffebee", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-lighten-4', 'hexacode' => "#ffcdd2", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-lighten-3', 'hexacode' => "#ef9a9a", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-lighten-2', 'hexacode' => "#e57373", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-lighten-1', 'hexacode' => "#ef5350", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red', 'hexacode' => "#f44336", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-darken-1', 'hexacode' => "#e53935", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-darken-2', 'hexacode' => "#d32f2f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-darken-3', 'hexacode' => "#c62828", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-darken-4', 'hexacode' => "#b71c1c", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-accent-1', 'hexacode' => "#ff8a80", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-accent-2', 'hexacode' => "#ff5252", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-accent-3', 'hexacode' => "#ff1744", 'is_default' => 0),
            array('type' => "bg", 'color' => 'red-accent-4', 'hexacode' => "#d50000", 'is_default' => 0),

            array('type' => "text", 'color' => 'red-lighten-5', 'hexacode' => "#ffebee", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-lighten-4', 'hexacode' => "#ffcdd2", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-lighten-3', 'hexacode' => "#ef9a9a", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-lighten-2', 'hexacode' => "#e57373", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-lighten-1', 'hexacode' => "#ef5350", 'is_default' => 0),
            array('type' => "text", 'color' => 'red', 'hexacode' => "#f44336", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-darken-1', 'hexacode' => "#e53935", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-darken-2', 'hexacode' => "#d32f2f", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-darken-3', 'hexacode' => "#c62828", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-darken-4', 'hexacode' => "#b71c1c", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-accent-1', 'hexacode' => "#ff8a80", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-accent-2', 'hexacode' => "#ff5252", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-accent-3', 'hexacode' => "#ff1744", 'is_default' => 0),
            array('type' => "text", 'color' => 'red-accent-4', 'hexacode' => "#d50000", 'is_default' => 0),

            // Pink

            array('type' => "bg", 'color' => 'pink-lighten-5', 'hexacode' => "#fce4ec", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-lighten-4', 'hexacode' => "#f8bbd0", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-lighten-3', 'hexacode' => "#f48fb1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-lighten-2', 'hexacode' => "#f06292", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-lighten-1', 'hexacode' => "#ec407a", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink', 'hexacode' => "#e91e63", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-darken-1', 'hexacode' => "#d81b60", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-darken-2', 'hexacode' => "#c2185b", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-darken-3', 'hexacode' => "#ad1457", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-darken-4', 'hexacode' => "#880e4f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-accent-1', 'hexacode' => "#ff80ab", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-accent-2', 'hexacode' => "#ff4081", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-accent-3', 'hexacode' => "#f50057", 'is_default' => 0),
            array('type' => "bg", 'color' => 'pink-accent-4', 'hexacode' => "#c51162", 'is_default' => 0),

            array('type' => "text", 'color' => 'pink-lighten-5', 'hexacode' => "#fce4ec", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-lighten-4', 'hexacode' => "#f8bbd0", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-lighten-3', 'hexacode' => "#f48fb1", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-lighten-2', 'hexacode' => "#f06292", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-lighten-1', 'hexacode' => "#ec407a", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink', 'hexacode' => "#e91e63", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-darken-1', 'hexacode' => "#d81b60", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-darken-2', 'hexacode' => "#c2185b", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-darken-3', 'hexacode' => "#ad1457", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-darken-4', 'hexacode' => "#880e4f", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-accent-1', 'hexacode' => "#ff80ab", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-accent-2', 'hexacode' => "#ff4081", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-accent-3', 'hexacode' => "#f50057", 'is_default' => 0),
            array('type' => "text", 'color' => 'pink-accent-4', 'hexacode' => "#c51162", 'is_default' => 0),

            // Purple

            array('type' => "bg", 'color' => 'purple-lighten-5', 'hexacode' => "#f3e5f5", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-lighten-4', 'hexacode' => "#e1bee7", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-lighten-3', 'hexacode' => "#ce93d8", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-lighten-2', 'hexacode' => "#ba68c8", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-lighten-1', 'hexacode' => "#ab47bc", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple', 'hexacode' => "#9c27b0", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-darken-1', 'hexacode' => "#8e24aa", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-darken-2', 'hexacode' => "#7b1fa2", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-darken-3', 'hexacode' => "#6a1b9a", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-darken-4', 'hexacode' => "#4a148c", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-accent-1', 'hexacode' => "#ea80fc", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-accent-2', 'hexacode' => "#e040fb", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-accent-3', 'hexacode' => "#d500f9", 'is_default' => 0),
            array('type' => "bg", 'color' => 'purple-accent-4', 'hexacode' => "#aa00ff", 'is_default' => 0),

            array('type' => "text", 'color' => 'purple-lighten-5', 'hexacode' => "#f3e5f5", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-lighten-4', 'hexacode' => "#e1bee7", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-lighten-3', 'hexacode' => "#ce93d8", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-lighten-2', 'hexacode' => "#ba68c8", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-lighten-1', 'hexacode' => "#ab47bc", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple', 'hexacode' => "#9c27b0", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-darken-1', 'hexacode' => "#8e24aa", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-darken-2', 'hexacode' => "#7b1fa2", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-darken-3', 'hexacode' => "#6a1b9a", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-darken-4', 'hexacode' => "#4a148c", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-accent-1', 'hexacode' => "#ea80fc", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-accent-2', 'hexacode' => "#e040fb", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-accent-3', 'hexacode' => "#d500f9", 'is_default' => 0),
            array('type' => "text", 'color' => 'purple-accent-4', 'hexacode' => "#aa00ff", 'is_default' => 0),

            //  Deep-Purple

            array('type' => "bg", 'color' => 'deep-purple-lighten-5', 'hexacode' => "#ede7f6", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-lighten-4', 'hexacode' => "#d1c4e9", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-lighten-3', 'hexacode' => "#b39ddb", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-lighten-2', 'hexacode' => "#9575cd", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-lighten-1', 'hexacode' => "#7e57c2", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple', 'hexacode' => "#673ab7", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-darken-1', 'hexacode' => "#5e35b1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-darken-2', 'hexacode' => "#512da8", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-darken-3', 'hexacode' => "#4527a0", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-darken-4', 'hexacode' => "#311b92", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-accent-1', 'hexacode' => "#b388ff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-accent-2', 'hexacode' => "#7c4dff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-accent-3', 'hexacode' => "#651fff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-purple-accent-4', 'hexacode' => "#6200ea", 'is_default' => 0),

            array('type' => "text", 'color' => 'deep-purple-lighten-5', 'hexacode' => "#ede7f6", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-lighten-4', 'hexacode' => "#d1c4e9", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-lighten-3', 'hexacode' => "#b39ddb", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-lighten-2', 'hexacode' => "#9575cd", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-lighten-1', 'hexacode' => "#7e57c2", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple', 'hexacode' => "#673ab7", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-darken-1', 'hexacode' => "#5e35b1", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-darken-2', 'hexacode' => "#512da8", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-darken-3', 'hexacode' => "#4527a0", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-darken-4', 'hexacode' => "#311b92", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-accent-1', 'hexacode' => "#b388ff", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-accent-2', 'hexacode' => "#7c4dff", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-accent-3', 'hexacode' => "#651fff", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-purple-accent-4', 'hexacode' => "#6200ea", 'is_default' => 0),

            // Indigo

            array('type' => "bg", 'color' => 'indigo-lighten-5', 'hexacode' => "#e8eaf6", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-lighten-4', 'hexacode' => "#c5cae9", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-lighten-3', 'hexacode' => "#9fa8da", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-lighten-2', 'hexacode' => "#7986cb", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-lighten-1', 'hexacode' => "#5c6bc0", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo', 'hexacode' => "#3f51b5", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-darken-1', 'hexacode' => "#3949ab", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-darken-2', 'hexacode' => "#303f9f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-darken-3', 'hexacode' => "#283593", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-darken-4', 'hexacode' => "#1a237e", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-accent-1', 'hexacode' => "#8c9eff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-accent-2', 'hexacode' => "#536dfe", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-accent-3', 'hexacode' => "#3d5afe", 'is_default' => 0),
            array('type' => "bg", 'color' => 'indigo-accent-4', 'hexacode' => "#304ffe", 'is_default' => 0),

            array('type' => "text", 'color' => 'indigo-lighten-5', 'hexacode' => "#e8eaf6", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-lighten-4', 'hexacode' => "#c5cae9", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-lighten-3', 'hexacode' => "#9fa8da", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-lighten-2', 'hexacode' => "#7986cb", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-lighten-1', 'hexacode' => "#5c6bc0", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo', 'hexacode' => "#3f51b5", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-darken-1', 'hexacode' => "#3949ab", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-darken-2', 'hexacode' => "#303f9f", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-darken-3', 'hexacode' => "#283593", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-darken-4', 'hexacode' => "#1a237e", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-accent-1', 'hexacode' => "#8c9eff", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-accent-2', 'hexacode' => "#536dfe", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-accent-3', 'hexacode' => "#3d5afe", 'is_default' => 0),
            array('type' => "text", 'color' => 'indigo-accent-4', 'hexacode' => "#304ffe", 'is_default' => 0),

            // blue

            array('type' => "bg", 'color' => 'blue-lighten-5', 'hexacode' => "#e3f2fd", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-lighten-4', 'hexacode' => "#bbdefb", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-lighten-3', 'hexacode' => "#90caf9", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-lighten-2', 'hexacode' => "#64b5f6", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-lighten-1', 'hexacode' => "#42a5f5", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue', 'hexacode' => "#2196f3", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-darken-1', 'hexacode' => "#1e88e5", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-darken-2', 'hexacode' => "#1976d2", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-darken-3', 'hexacode' => "#1565c0", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-darken-4', 'hexacode' => "#0d47a1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-accent-1', 'hexacode' => "#82b1ff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-accent-2', 'hexacode' => "#448aff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-accent-3', 'hexacode' => "#2979ff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-accent-4', 'hexacode' => "#2962ff", 'is_default' => 0),

            array('type' => "text", 'color' => 'blue-lighten-5', 'hexacode' => "#e3f2fd", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-lighten-4', 'hexacode' => "#bbdefb", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-lighten-3', 'hexacode' => "#90caf9", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-lighten-2', 'hexacode' => "#64b5f6", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-lighten-1', 'hexacode' => "#42a5f5", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue', 'hexacode' => "#2196f3", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-darken-1', 'hexacode' => "#1e88e5", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-darken-2', 'hexacode' => "#1976d2", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-darken-3', 'hexacode' => "#1565c0", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-darken-4', 'hexacode' => "#0d47a1", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-accent-1', 'hexacode' => "#82b1ff", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-accent-2', 'hexacode' => "#448aff", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-accent-3', 'hexacode' => "#2979ff", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-accent-4', 'hexacode' => "#2962ff", 'is_default' => 0),

            // light-blue

            array('type' => "bg", 'color' => 'light-blue-lighten-5', 'hexacode' => "#e1f5fe", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-lighten-4', 'hexacode' => "#b3e5fc", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-lighten-3', 'hexacode' => "#81d4fa", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-lighten-2', 'hexacode' => "#4fc3f7", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-lighten-1', 'hexacode' => "#29b6f6", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue', 'hexacode' => "#03a9f4", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-darken-1', 'hexacode' => "#039be5", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-darken-2', 'hexacode' => "#0288d1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-darken-3', 'hexacode' => "#0277bd", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-darken-4', 'hexacode' => "#01579b", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-accent-1', 'hexacode' => "#80d8ff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-accent-2', 'hexacode' => "#40c4ff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-accent-3', 'hexacode' => "#00b0ff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-blue-accent-4', 'hexacode' => "#0091ea", 'is_default' => 0),

            array('type' => "text", 'color' => 'light-blue-lighten-5', 'hexacode' => "#e1f5fe", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-lighten-4', 'hexacode' => "#b3e5fc", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-lighten-3', 'hexacode' => "#81d4fa", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-lighten-2', 'hexacode' => "#4fc3f7", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-lighten-1', 'hexacode' => "#29b6f6", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue', 'hexacode' => "#03a9f4", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-darken-1', 'hexacode' => "#039be5", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-darken-2', 'hexacode' => "#0288d1", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-darken-3', 'hexacode' => "#0277bd", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-darken-4', 'hexacode' => "#01579b", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-accent-1', 'hexacode' => "#80d8ff", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-accent-2', 'hexacode' => "#40c4ff", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-accent-3', 'hexacode' => "#00b0ff", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-blue-accent-4', 'hexacode' => "#0091ea", 'is_default' => 0),

            // cyan

            array('type' => "bg", 'color' => 'cyan-lighten-5', 'hexacode' => "#e0f7fa", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-lighten-4', 'hexacode' => "#b2ebf2", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-lighten-3', 'hexacode' => "#80deea", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-lighten-2', 'hexacode' => "#4dd0e1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-lighten-1', 'hexacode' => "#26c6da", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan', 'hexacode' => "#00bcd4", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-darken-1', 'hexacode' => "#00acc1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-darken-2', 'hexacode' => "#0097a7", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-darken-3', 'hexacode' => "#00838f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-darken-4', 'hexacode' => "#006064", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-accent-1', 'hexacode' => "#84ffff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-accent-2', 'hexacode' => "#18ffff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-accent-3', 'hexacode' => "#00e5ff", 'is_default' => 0),
            array('type' => "bg", 'color' => 'cyan-accent-4', 'hexacode' => "#00b8d4", 'is_default' => 0),

            array('type' => "text", 'color' => 'cyan-lighten-5', 'hexacode' => "#e0f7fa", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-lighten-4', 'hexacode' => "#b2ebf2", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-lighten-3', 'hexacode' => "#80deea", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-lighten-2', 'hexacode' => "#4dd0e1", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-lighten-1', 'hexacode' => "#26c6da", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan', 'hexacode' => "#00bcd4", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-darken-1', 'hexacode' => "#00acc1", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-darken-2', 'hexacode' => "#0097a7", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-darken-3', 'hexacode' => "#00838f", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-darken-4', 'hexacode' => "#006064", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-accent-1', 'hexacode' => "#84ffff", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-accent-2', 'hexacode' => "#18ffff", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-accent-3', 'hexacode' => "#00e5ff", 'is_default' => 0),
            array('type' => "text", 'color' => 'cyan-accent-4', 'hexacode' => "#00b8d4", 'is_default' => 0),

            // teal

            array('type' => "bg", 'color' => 'teal-lighten-5', 'hexacode' => "#e0f2f1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-lighten-4', 'hexacode' => "#b2dfdb", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-lighten-3', 'hexacode' => "#80cbc4", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-lighten-2', 'hexacode' => "#4db6ac", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-lighten-1', 'hexacode' => "#26a69a", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal', 'hexacode' => "#009688", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-darken-1', 'hexacode' => "#00897b", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-darken-2', 'hexacode' => "#00796b", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-darken-3', 'hexacode' => "#00695c", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-darken-4', 'hexacode' => "#004d40", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-accent-1', 'hexacode' => "#a7ffeb", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-accent-2', 'hexacode' => "#64ffda", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-accent-3', 'hexacode' => "#1de9b6", 'is_default' => 0),
            array('type' => "bg", 'color' => 'teal-accent-4', 'hexacode' => "#00bfa5", 'is_default' => 0),

            array('type' => "text", 'color' => 'teal-lighten-5', 'hexacode' => "#e0f2f1", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-lighten-4', 'hexacode' => "#b2dfdb", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-lighten-3', 'hexacode' => "#80cbc4", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-lighten-2', 'hexacode' => "#4db6ac", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-lighten-1', 'hexacode' => "#26a69a", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal', 'hexacode' => "#009688", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-darken-1', 'hexacode' => "#00897b", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-darken-2', 'hexacode' => "#00796b", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-darken-3', 'hexacode' => "#00695c", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-darken-4', 'hexacode' => "#004d40", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-accent-1', 'hexacode' => "#a7ffeb", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-accent-2', 'hexacode' => "#64ffda", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-accent-3', 'hexacode' => "#1de9b6", 'is_default' => 0),
            array('type' => "text", 'color' => 'teal-accent-4', 'hexacode' => "#00bfa5", 'is_default' => 0),

            // green

            array('type' => "bg", 'color' => 'green-lighten-5', 'hexacode' => "#e8f5e9", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-lighten-4', 'hexacode' => "#c8e6c9", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-lighten-3', 'hexacode' => "#a5d6a7", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-lighten-2', 'hexacode' => "#81c784", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-lighten-1', 'hexacode' => "#66bb6a", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green', 'hexacode' => "#4caf50", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-darken-1', 'hexacode' => "#43a047", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-darken-2', 'hexacode' => "#388e3c", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-darken-3', 'hexacode' => "#2e7d32", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-darken-4', 'hexacode' => "#1b5e20", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-accent-1', 'hexacode' => "#b9f6ca", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-accent-2', 'hexacode' => "#69f0ae", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-accent-3', 'hexacode' => "#00e676", 'is_default' => 0),
            array('type' => "bg", 'color' => 'green-accent-4', 'hexacode' => "#00c853", 'is_default' => 0),

            array('type' => "text", 'color' => 'green-lighten-5', 'hexacode' => "#e8f5e9", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-lighten-4', 'hexacode' => "#c8e6c9", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-lighten-3', 'hexacode' => "#a5d6a7", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-lighten-2', 'hexacode' => "#81c784", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-lighten-1', 'hexacode' => "#66bb6a", 'is_default' => 0),
            array('type' => "text", 'color' => 'green', 'hexacode' => "#4caf50", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-darken-1', 'hexacode' => "#43a047", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-darken-2', 'hexacode' => "#388e3c", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-darken-3', 'hexacode' => "#2e7d32", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-darken-4', 'hexacode' => "#1b5e20", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-accent-1', 'hexacode' => "#b9f6ca", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-accent-2', 'hexacode' => "#69f0ae", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-accent-3', 'hexacode' => "#00e676", 'is_default' => 0),
            array('type' => "text", 'color' => 'green-accent-4', 'hexacode' => "#00c853", 'is_default' => 0),

            // light-green

            array('type' => "bg", 'color' => 'light-green-lighten-5', 'hexacode' => "#f1f8e9", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-lighten-4', 'hexacode' => "#dcedc8", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-lighten-3', 'hexacode' => "#c5e1a5", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-lighten-2', 'hexacode' => "#aed581", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-lighten-1', 'hexacode' => "#9ccc65", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green', 'hexacode' => "#8bc34a", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-darken-1', 'hexacode' => "#7cb342", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-darken-2', 'hexacode' => "#689f38", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-darken-3', 'hexacode' => "#558b2f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-darken-4', 'hexacode' => "#33691e", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-accent-1', 'hexacode' => "#ccff90", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-accent-2', 'hexacode' => "#b2ff59", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-accent-3', 'hexacode' => "#76ff03", 'is_default' => 0),
            array('type' => "bg", 'color' => 'light-green-accent-4', 'hexacode' => "#64dd17", 'is_default' => 0),

            array('type' => "text", 'color' => 'light-green-lighten-5', 'hexacode' => "#f1f8e9", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-lighten-4', 'hexacode' => "#dcedc8", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-lighten-3', 'hexacode' => "#c5e1a5", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-lighten-2', 'hexacode' => "#aed581", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-lighten-1', 'hexacode' => "#9ccc65", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green', 'hexacode' => "#8bc34a", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-darken-1', 'hexacode' => "#7cb342", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-darken-2', 'hexacode' => "#689f38", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-darken-3', 'hexacode' => "#558b2f", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-darken-4', 'hexacode' => "#33691e", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-accent-1', 'hexacode' => "#ccff90", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-accent-2', 'hexacode' => "#b2ff59", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-accent-3', 'hexacode' => "#76ff03", 'is_default' => 0),
            array('type' => "text", 'color' => 'light-green-accent-4', 'hexacode' => "#64dd17", 'is_default' => 0),

            // lime

            array('type' => "bg", 'color' => 'lime-lighten-5', 'hexacode' => "#f9fbe7", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-lighten-4', 'hexacode' => "#f0f4c3", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-lighten-3', 'hexacode' => "#e6ee9c", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-lighten-2', 'hexacode' => "#dce775", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-lighten-1', 'hexacode' => "#d4e157", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime', 'hexacode' => "#cddc39", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-darken-1', 'hexacode' => "#c0ca33", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-darken-2', 'hexacode' => "#afb42b", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-darken-3', 'hexacode' => "#9e9d24", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-darken-4', 'hexacode' => "#827717", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-accent-1', 'hexacode' => "#f4ff81", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-accent-2', 'hexacode' => "#eeff41", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-accent-3', 'hexacode' => "#c6ff00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'lime-accent-4', 'hexacode' => "#aeea00", 'is_default' => 0),

            array('type' => "text", 'color' => 'lime-lighten-5', 'hexacode' => "#f9fbe7", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-lighten-4', 'hexacode' => "#f0f4c3", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-lighten-3', 'hexacode' => "#e6ee9c", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-lighten-2', 'hexacode' => "#dce775", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-lighten-1', 'hexacode' => "#d4e157", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime', 'hexacode' => "#cddc39", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-darken-1', 'hexacode' => "#c0ca33", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-darken-2', 'hexacode' => "#afb42b", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-darken-3', 'hexacode' => "#9e9d24", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-darken-4', 'hexacode' => "#827717", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-accent-1', 'hexacode' => "#f4ff81", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-accent-2', 'hexacode' => "#eeff41", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-accent-3', 'hexacode' => "#c6ff00", 'is_default' => 0),
            array('type' => "text", 'color' => 'lime-accent-4', 'hexacode' => "#aeea00", 'is_default' => 0),

            // yellow

            array('type' => "bg", 'color' => 'yellow-lighten-5', 'hexacode' => "#fffde7", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-lighten-4', 'hexacode' => "#fff9c4", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-lighten-3', 'hexacode' => "#fff59d", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-lighten-2', 'hexacode' => "#fff176", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-lighten-1', 'hexacode' => "#ffee58", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow', 'hexacode' => "#ffeb3b", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-darken-1', 'hexacode' => "#fdd835", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-darken-2', 'hexacode' => "#fbc02d", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-darken-3', 'hexacode' => "#f9a825", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-darken-4', 'hexacode' => "#f57f17", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-accent-1', 'hexacode' => "#ffff8d", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-accent-2', 'hexacode' => "#ffff00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-accent-3', 'hexacode' => "#ffea00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'yellow-accent-4', 'hexacode' => "#ffd600", 'is_default' => 0),

            array('type' => "text", 'color' => 'yellow-lighten-5', 'hexacode' => "#fffde7", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-lighten-4', 'hexacode' => "#fff9c4", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-lighten-3', 'hexacode' => "#fff59d", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-lighten-2', 'hexacode' => "#fff176", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-lighten-1', 'hexacode' => "#ffee58", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow', 'hexacode' => "#ffeb3b", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-darken-1', 'hexacode' => "#fdd835", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-darken-2', 'hexacode' => "#fbc02d", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-darken-3', 'hexacode' => "#f9a825", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-darken-4', 'hexacode' => "#f57f17", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-accent-1', 'hexacode' => "#ffff8d", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-accent-2', 'hexacode' => "#ffff00", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-accent-3', 'hexacode' => "#ffea00", 'is_default' => 0),
            array('type' => "text", 'color' => 'yellow-accent-4', 'hexacode' => "#ffd600", 'is_default' => 0),

            // amber

            array('type' => "bg", 'color' => 'amber-lighten-5', 'hexacode' => "#fff8e1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-lighten-4', 'hexacode' => "#ffecb3", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-lighten-3', 'hexacode' => "#ffe082", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-lighten-2', 'hexacode' => "#ffd54f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-lighten-1', 'hexacode' => "#ffca28", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber', 'hexacode' => "#ffc107", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-darken-1', 'hexacode' => "#ffb300", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-darken-2', 'hexacode' => "#ffa000", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-darken-3', 'hexacode' => "#ff8f00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-darken-4', 'hexacode' => "#ff6f00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-accent-1', 'hexacode' => "#ffe57f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-accent-2', 'hexacode' => "#ffd740", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-accent-3', 'hexacode' => "#ffc400", 'is_default' => 0),
            array('type' => "bg", 'color' => 'amber-accent-4', 'hexacode' => "#ffab00", 'is_default' => 0),

            array('type' => "text", 'color' => 'amber-lighten-5', 'hexacode' => "#fff8e1", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-lighten-4', 'hexacode' => "#ffecb3", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-lighten-3', 'hexacode' => "#ffe082", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-lighten-2', 'hexacode' => "#ffd54f", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-lighten-1', 'hexacode' => "#ffca28", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber', 'hexacode' => "#ffc107", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-darken-1', 'hexacode' => "#ffb300", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-darken-2', 'hexacode' => "#ffa000", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-darken-3', 'hexacode' => "#ff8f00", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-darken-4', 'hexacode' => "#ff6f00", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-accent-1', 'hexacode' => "#ffe57f", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-accent-2', 'hexacode' => "#ffd740", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-accent-3', 'hexacode' => "#ffc400", 'is_default' => 0),
            array('type' => "text", 'color' => 'amber-accent-4', 'hexacode' => "#ffab00", 'is_default' => 0),

            // orange

            array('type' => "bg", 'color' => 'orange-lighten-5', 'hexacode' => "#fff3e0", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-lighten-4', 'hexacode' => "#ffe0b2", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-lighten-3', 'hexacode' => "#ffcc80", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-lighten-2', 'hexacode' => "#ffb74d", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-lighten-1', 'hexacode' => "#ffa726", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange', 'hexacode' => "#ff9800", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-darken-1', 'hexacode' => "#fb8c00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-darken-2', 'hexacode' => "#f57c00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-darken-3', 'hexacode' => "#ef6c00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-darken-4', 'hexacode' => "#00c5d0", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-accent-1', 'hexacode' => "#ffd180", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-accent-2', 'hexacode' => "#ffab40", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-accent-3', 'hexacode' => "#ff9100", 'is_default' => 0),
            array('type' => "bg", 'color' => 'orange-accent-4', 'hexacode' => "#ff6d00", 'is_default' => 0),

            array('type' => "text", 'color' => 'orange-lighten-5', 'hexacode' => "#fff3e0", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-lighten-4', 'hexacode' => "#ffe0b2", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-lighten-3', 'hexacode' => "#ffcc80", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-lighten-2', 'hexacode' => "#ffb74d", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-lighten-1', 'hexacode' => "#ffa726", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange', 'hexacode' => "#ff9800", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-darken-1', 'hexacode' => "#fb8c00", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-darken-2', 'hexacode' => "#f57c00", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-darken-3', 'hexacode' => "#ef6c00", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-darken-4', 'hexacode' => "#00c5d0", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-accent-1', 'hexacode' => "#ffd180", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-accent-2', 'hexacode' => "#ffab40", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-accent-3', 'hexacode' => "#ff9100", 'is_default' => 0),
            array('type' => "text", 'color' => 'orange-accent-4', 'hexacode' => "#ff6d00", 'is_default' => 0),

            // deep-orange

            array('type' => "bg", 'color' => 'deep-orange-lighten-5', 'hexacode' => "#fbe9e7", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-lighten-4', 'hexacode' => "#ffccbc", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-lighten-3', 'hexacode' => "#ffab91", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-lighten-2', 'hexacode' => "#ff8a65", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-lighten-1', 'hexacode' => "#ff7043", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange', 'hexacode' => "#ff5722", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-darken-1', 'hexacode' => "#f4511e", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-darken-2', 'hexacode' => "#e64a19", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-darken-3', 'hexacode' => "#d84315", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-darken-4', 'hexacode' => "#bf360c", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-accent-1', 'hexacode' => "#ff9e80", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-accent-2', 'hexacode' => "#ff6e40", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-accent-3', 'hexacode' => "#ff3d00", 'is_default' => 0),
            array('type' => "bg", 'color' => 'deep-orange-accent-4', 'hexacode' => "#dd2c00", 'is_default' => 0),

            array('type' => "text", 'color' => 'deep-orange-lighten-5', 'hexacode' => "#fbe9e7", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-lighten-4', 'hexacode' => "#ffccbc", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-lighten-3', 'hexacode' => "#ffab91", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-lighten-2', 'hexacode' => "#ff8a65", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-lighten-1', 'hexacode' => "#ff7043", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange', 'hexacode' => "#ff5722", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-darken-1', 'hexacode' => "#f4511e", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-darken-2', 'hexacode' => "#e64a19", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-darken-3', 'hexacode' => "#d84315", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-darken-4', 'hexacode' => "#bf360c", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-accent-1', 'hexacode' => "#ff9e80", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-accent-2', 'hexacode' => "#ff6e40", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-accent-3', 'hexacode' => "#ff3d00", 'is_default' => 0),
            array('type' => "text", 'color' => 'deep-orange-accent-4', 'hexacode' => "#dd2c00", 'is_default' => 0),

            // brown

            array('type' => "bg", 'color' => 'brown-lighten-5', 'hexacode' => "#efebe9", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown-lighten-4', 'hexacode' => "#d7ccc8", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown-lighten-3', 'hexacode' => "#bcaaa4", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown-lighten-2', 'hexacode' => "#a1887f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown-lighten-1', 'hexacode' => "#8d6e63", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown', 'hexacode' => "#795548", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown-darken-1', 'hexacode' => "#6d4c41", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown-darken-2', 'hexacode' => "#5d4037", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown-darken-3', 'hexacode' => "#4e342e", 'is_default' => 0),
            array('type' => "bg", 'color' => 'brown-darken-4', 'hexacode' => "#3e2723", 'is_default' => 0),

            array('type' => "text", 'color' => 'brown-lighten-5', 'hexacode' => "#efebe9", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown-lighten-4', 'hexacode' => "#d7ccc8", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown-lighten-3', 'hexacode' => "#bcaaa4", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown-lighten-2', 'hexacode' => "#a1887f", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown-lighten-1', 'hexacode' => "#8d6e63", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown', 'hexacode' => "#795548", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown-darken-1', 'hexacode' => "#6d4c41", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown-darken-2', 'hexacode' => "#5d4037", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown-darken-3', 'hexacode' => "#4e342e", 'is_default' => 0),
            array('type' => "text", 'color' => 'brown-darken-4', 'hexacode' => "#3e2723", 'is_default' => 0),

            // grey

            array('type' => "bg", 'color' => 'grey-lighten-5', 'hexacode' => "#fafafa", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey-lighten-4', 'hexacode' => "#f5f5f5", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey-lighten-3', 'hexacode' => "#eeeeee", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey-lighten-2', 'hexacode' => "#e0e0e0", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey-lighten-1', 'hexacode' => "#bdbdbd", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey', 'hexacode' => "#9e9e9e", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey-darken-1', 'hexacode' => "#757575", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey-darken-2', 'hexacode' => "#616161", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey-darken-3', 'hexacode' => "#424242", 'is_default' => 0),
            array('type' => "bg", 'color' => 'grey-darken-4', 'hexacode' => "#212121", 'is_default' => 0),

            array('type' => "text", 'color' => 'grey-lighten-5', 'hexacode' => "#fafafa", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey-lighten-4', 'hexacode' => "#f5f5f5", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey-lighten-3', 'hexacode' => "#eeeeee", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey-lighten-2', 'hexacode' => "#e0e0e0", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey-lighten-1', 'hexacode' => "#bdbdbd", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey', 'hexacode' => "#9e9e9e", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey-darken-1', 'hexacode' => "#757575", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey-darken-2', 'hexacode' => "#616161", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey-darken-3', 'hexacode' => "#424242", 'is_default' => 0),
            array('type' => "text", 'color' => 'grey-darken-4', 'hexacode' => "#212121", 'is_default' => 0),

            // blue-grey

            array('type' => "bg", 'color' => 'blue-grey-lighten-5', 'hexacode' => "#eceff1", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey-lighten-4', 'hexacode' => "#cfd8dc", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey-lighten-3', 'hexacode' => "#b0bec5", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey-lighten-2', 'hexacode' => "#90a4ae", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey-lighten-1', 'hexacode' => "#78909c", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey', 'hexacode' => "#607d8b", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey-darken-1', 'hexacode' => "#546e7a", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey-darken-2', 'hexacode' => "#455a64", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey-darken-3', 'hexacode' => "#37474f", 'is_default' => 0),
            array('type' => "bg", 'color' => 'blue-grey-darken-4', 'hexacode' => "#263238", 'is_default' => 0),

            array('type' => "text", 'color' => 'blue-grey-lighten-5', 'hexacode' => "#eceff1", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey-lighten-4', 'hexacode' => "#cfd8dc", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey-lighten-3', 'hexacode' => "#b0bec5", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey-lighten-2', 'hexacode' => "#90a4ae", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey-lighten-1', 'hexacode' => "#78909c", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey', 'hexacode' => "#607d8b", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey-darken-1', 'hexacode' => "#546e7a", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey-darken-2', 'hexacode' => "#455a64", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey-darken-3', 'hexacode' => "#37474f", 'is_default' => 0),
            array('type' => "text", 'color' => 'blue-grey-darken-4', 'hexacode' => "#263238", 'is_default' => 0),

        );
        DB::table('colors')->insert($colors);
    }
}
